CREATE TABLE IF NOT EXISTS engagement_file_catalog (
    file_id VARCHAR(100) PRIMARY KEY,
    firm_id VARCHAR(100) NOT NULL,
    template_id VARCHAR(100) NOT NULL,
    template_version VARCHAR(100) NOT NULL,
    market VARCHAR(40) NOT NULL,
    region VARCHAR(40) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_file_template_market
    ON engagement_file_catalog(template_id, market, file_id);

CREATE TABLE IF NOT EXISTS template_publication (
    publication_id VARCHAR(100) PRIMARY KEY,
    template_id VARCHAR(100) NOT NULL,
    target_version VARCHAR(100) NOT NULL,
    market VARCHAR(40) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    scan_cursor VARCHAR(100),
    lease_token VARCHAR(100),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    total_tasks BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_publication_work
    ON template_publication(status, lease_expires_at, published_at);

CREATE TABLE IF NOT EXISTS fan_out_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id VARCHAR(100) NOT NULL,
    file_id VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_token VARCHAR(100),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_publication FOREIGN KEY (publication_id)
        REFERENCES template_publication(publication_id),
    CONSTRAINT fk_task_file FOREIGN KEY (file_id)
        REFERENCES engagement_file_catalog(file_id),
    CONSTRAINT uk_task_publication_file UNIQUE (publication_id, file_id)
);

CREATE INDEX IF NOT EXISTS idx_task_dispatch
    ON fan_out_task(status, next_attempt_at, lease_expires_at, id);

